### ISSUE TITLE
[MetadataImageOptimizer] Images got lost sporadically when metadata saved

### ISSUE THREAD

**Issue by nikolay-borzov** [UrbanCMC/PlayniteExtensions#10]
| Header | Header |
|--------|--------|
| OS: | Microsoft Windows 10 Pro (10.0.19045 Build 19045) |
| Playnite: | 10.34|
| MetadataImageOptimizer: | 1.5 |

Current settings:

- Always optimize images when editing a game
- Run in background

Background:
- Optimize
- Format: WebP (Lossy)
- Max Size: 1920x1080

Cover:
- Optimize
- Format: WebP (Lossy)
- Max Size: 800x800

Icon:
- Optimize
- Format: PNG
- Max Size: 256x256

Quality:
- JPG Quality: 90
- PNG Compression Level: 7
- WebP Encoding Method: 6 (Slowest)
- WebP Quality: 90
---

1. The game had background in JPEG format and icon in PNG format
2. "Edit" game metadata and update some images (e.g. icon)
3. Click "Save" and quickly edit and save metadata again
4. Icon and background images are removed and the log has:

```text
17-11 23:37:46.937|ERROR|MetadataImageOptimizer#MetadataImageOptimizer:Error while optimizing background image for 'Alien Shooter - Last Hope'.
System.IO.FileNotFoundException: Could not find file 'G:\Playnite\library\files\b44908a0-9599-4d24-bb54-3e5c2d22ac67\12ca5f7c-d57d-4fb2-a874-475f79e32a05.jpg'.
File name: 'G:\Playnite\library\files\b44908a0-9599-4d24-bb54-3e5c2d22ac67\12ca5f7c-d57d-4fb2-a874-475f79e32a05.jpg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SixLabors.ImageSharp.IO.LocalFileSystem.OpenRead(String path)
   at SixLabors.ImageSharp.Image.Load(Configuration configuration, String path, IImageFormat& format)
   at MetadataImageOptimizer.ImageOptimizer.Optimize(String imagePath, ImageTypeSettings imageSettings, QualitySettings qualitySettings)
   at MetadataImageOptimizer.MetadataImageOptimizer.OptimizeGame(Guid gameId, Boolean optimizeBackground, Boolean optimizeCover, Boolean optimizeIcon)
17-11 23:37:47.013|ERROR|MetadataImageOptimizer#MetadataImageOptimizer:Error while optimizing icon for 'Alien Shooter - Last Hope'.
System.IO.FileNotFoundException: Could not find file 'G:\Playnite\library\files\b44908a0-9599-4d24-bb54-3e5c2d22ac67\688e29d5-b3e3-4c1b-877e-e4a89e98bdd8.ico'.
File name: 'G:\Playnite\library\files\b44908a0-9599-4d24-bb54-3e5c2d22ac67\688e29d5-b3e3-4c1b-877e-e4a89e98bdd8.ico'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at MetadataImageOptimizer.ImageOptimizer.IcoToHighQualityImage(String imagePath)
   at MetadataImageOptimizer.ImageOptimizer.Optimize(String imagePath, ImageTypeSettings imageSettings, QualitySettings qualitySettings)
   at MetadataImageOptimizer.MetadataImageOptimizer.OptimizeGame(Guid gameId, Boolean optimizeBackground, Boolean optimizeCover, Boolean optimizeIcon)
17-11 23:37:47.268|ERROR|SystemChecker#Common:Error on CheckOS(): Try to refresh the plugin data for Alien Shooter - Last Hope|C:\Projects\C#\Lacro59\playnite-systemchecker-plugin\source\Services\SystemApi.cs|75
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
   at System.Text.RegularExpressions.MatchCollection.get_Item(Int32 i)
   at SystemChecker.Services.SystemApi.CheckOS(String systemOs, List`1 requierementOs) in C:\Projects\C#\Lacro59\playnite-systemchecker-plugin\source\Services\SystemApi.cs:line 75
```

**Comment by UrbanCMC** [comment]
Thanks for the report.
This should be fixed in v1.6 as far as I can tell from my tests.
